### ISSUE TITLE
im getting this error 

### ISSUE THREAD

**Issue by Zakariagtse1** [Tomato6966/Multipurpose-discord-bot#11]
=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'REMIND')
    at CronJob.<anonymous> (C:\Users\Administrator\Desktop\Multipurpose-discord-bot-main\handlers\mute.js:65:32)
    at CronJob.fireOnTick (C:\Users\Administrator\Desktop\Multipurpose-discord-bot-main\node_modules\cron\lib\cron.js:600:23)
    at Timeout.callbackWrapper [as _onTimeout] (C:\Users\Administrator\Desktop\Multipurpose-discord-bot-main\node_modules\cron\lib\cron.js:667:10)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7)
=== UNHANDLED REJECTION ===

**Comment by Tomato6966** [comment]
make sure to install it right and dont uncomment loaddb.js
