### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by LeviAckerman1234** [Tomato6966/Multipurpose-discord-bot#114]
/Users/myname/Applications/visual/Multipurpose-discord-bot/slashCommands/.DS_Store:1

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/myna,e/Applications/visual/Multipurpose-discord-bot/handlers/slashCommands.js:104:16
    at Array.forEach (<anonymous>)

getting this error the bot is online n only responds to being pinged no commands are responding but the bot stays online please help me

**Comment by LeviAckerman1234** [comment]
can anyone help?

**Comment by LeviAckerman1234** [comment]
can anyone help me?

**Comment by Rocky-pup** [comment]
idk, i haven't problem with it

**Comment by LeviAckerman1234** [comment]
what can i do tho

**Comment by LeviAckerman1234** [comment]
i also get this 
[x] :: Now loading the Commands ...
Error: ENOTDIR: not a directory, scandir './commands/.DS_Store/'
    at readdirSync (node:fs:1390:3)
    at /Users/myname/Applications/visual/Multipurpose-discord-bot/handlers/command.js:14:24
    at Array.forEach (<anonymous>)
    at module.exports (/Users/myname/Applications/visual/Multipurpose-discord-bot/handlers/command.js:13:32)
    at /Users/myname/Applications/visual/Multipurpose-discord-bot/index.js:123:43
    at Array.forEach (<anonymous>)
    at requirehandlers (/Users/myname/Applications/visual/Multipurpose-discord-bot/index.js:122:102)
    at Object.<anonymous> (/Users/myname/Applications/visual/Multipurpose-discord-bot/index.js:141:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[x] :: LOADED THE 0 COMMANDS after: 95ms

**Comment by Rocky-pup** [comment]
Your code like this?
![image](https://user-images.githubusercontent.com/83218418/162567905-acf1466c-c8b6-4c2c-87ad-1aeaf8c4e6c6.png)

**Comment by Rocky-pup** [comment]
bc of this error bot not loading commands

**Comment by Rocky-pup** [comment]
or your folder "commands" contains 1 extra file, .DS_Store, commands folder need to be like this, without hidden files:
![image](https://user-images.githubusercontent.com/83218418/162568031-864f9a59-42a5-482a-8689-a6079483e9b0.png)

**Comment by Rocky-pup** [comment]
DS_STORE extension stores folder view settings in Mac OS X, includes information about folder window location, window size, view options...
Try delete this, it hidden, but JS see everything

**Comment by Rocky-pup** [comment]
it's your local bug, so you can close issue

**Comment by hotsu0p** [comment]
I am getting the same issue
