### ISSUE TITLE
Some bugs I found

### ISSUE THREAD

**Issue by ROB0520** [Tomato6966/Multipurpose-discord-bot#12]
Here are some bugs that I found in the bot as I was doing some testing

1. Soundboard commands cause an error when removing the reaction as the bot leaves. Just add `await` before `message.react` in `Line 24` and it should work

2. Translate Command has an embed color error at ``Line 34``

3. ``2024.js``(Minigame Command) isnt the right file name, as it is the **2048** command

**Comment by itzhy22** [comment]
at Object.module.exports [as MESSAGE_CREATE] (/home/runner/bot1/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/bot1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/home/runner/bot1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/bot1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/bot1/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/home/runner/bot1/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (/home/runner/bot1/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/runner/bot1/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/runner/bot1/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/runner/bot1/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.socketOnData (/home/runner/bot1/node_modules/ws/lib/websocket.js:1192:35)
    at TLSSocket.emit (node:events:390:28)

**Comment by itzhy22** [comment]
at Object.run (/home/runner/bot1/commands/💪 Setup/setup-mute.js:36:7)
    at module.exports (/home/runner/bot1/events/guild/messageCreate.js:296:17)
    at Client.emit (node:events:402:35)
    at MessageCreateAction.handle (/home/runner/bot1/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/bot1/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/bot1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/home/runner/bot1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/bot1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/bot1/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/home/runner/bot1/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (/home/runner/bot1/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/runner/bot1/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/runner/bot1/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/runner/bot1/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.socketOnData (/home/runner/bot1/node_modules/ws/lib/websocket.js:1192:35)
    at TLSSocket.emit (node:events:390:28)

**Comment by Tomato6966** [comment]
> Here are some bugs that I found in the bot as I was doing some testing
> 
> 1. Soundboard commands cause an error when removing the reaction as the bot leaves. Just add `await` before `message.react` in `Line 24` and it should work
> 2. Translate Command has an embed color error at `Line 34`
> 3. `2024.js`(Minigame Command) isnt the right file name, as it is the **2048** command

Thanks for those reports, will be fixxed soon (2024, i can't change the name of it, as the shop bots would cause issues... ik.... welp u could change it for yourself, the commandname itsself is 2048 (its defined in the file)

**Comment by Tomato6966** [comment]
> 

Setup Mute is not done yet ;)
