### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by DmitriyyStanin** [Tomato6966/Multipurpose-discord-bot#127]
Multipurpose-discord-bot-2/handlers/erela_events/events.js:97
let channel = guild.channels.cache.get(client.musicsettings.get(player.guild, "channel"));
^^^

SyntaxError: Lexical declaration cannot appear in a single-statement context
at Object.compileFunction (node:vm:352:18)
at wrapSafe (node:internal/modules/cjs/loader:1032:15)
at Module._compile (node:internal/modules/cjs/loader:1067:27)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at module.exports (/home/runner/Multipurpose-discord-bot-2/handlers/erela_events/creation.js:45:7)
at module.exports (/home/runner/Multipurpose-discord-bot-2/handlers/erelahandler.js:5:39)
at /home/runner/Multipurpose-discord-bot-2/index.js:123:43
at Array.forEach ()
at requirehandlers (/home/runner/Multipurpose-discord-bot-2/index.js:122:102)
at Object. (/home/runner/Multipurpose-discord-bot-2/index.js:141:3)
at Module._compile (node:internal/modules/cjs/loader:1103:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
at node:internal/main/run_main_module:17:47
Error: Received one or more errors
at ArrayValidator.handle (/home/runner/Multipurpose-discord-bot-2/node_modules/@sapphire/shapeshift/dist/index.js:400:70)
at ArrayValidator.parse (/home/runner/Multipurpose-discord-bot-2/node_modules/@sapphire/shapeshift/dist/index.js:114:88)
at MixedClass.addChoices (/home/runner/Multipurpose-discord-bot-2/node_modules/@discordjs/builders/dist/index.js:1138:22)
at /home/runner/Multipurpose-discord-bot-2/handlers/slashCommands.js:77:14
at MixedClass._sharedAddOptionMethod (/home/runner/Multipurpose-discord-bot-2/node_modules/@discordjs/builders/dist/index.js:1334:50)
at MixedClass.addStringOption (/home/runner/Multipurpose-discord-bot-2/node_modules/@discordjs/builders/dist/index.js:1323:17)
at /home/runner/Multipurpose-discord-bot-2/handlers/slashCommands.js:75:23
at MixedClass.addSubcommand (/home/runner/Multipurpose-discord-bot-2/node_modules/@discordjs/builders/dist/index.js:1429:50)
at /home/runner/Multipurpose-discord-bot-2/handlers/slashCommands.js:50:9
at Array.forEach ()
at module.exports (/home/runner/Multipurpose-discord-bot-2/handlers/slashCommands.js:36:41)
at /home/runner/Multipurpose-discord-bot-2/index.js:123:43
at Array.forEach ()
at requirehandlers (/home/runner/Multipurpose-discord-bot-2/index.js:122:102)
at Object. (/home/runner/Multipurpose-discord-bot-2/index.js:141:3)
at Module._compile (node:internal/modules/cjs/loader:1103:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
at node:internal/main/run_main_module:17:47

**Comment by Rocky-pup** [comment]
On which command error? 
What you do before the error?

**Comment by DmitriyyStanin** [comment]
When the bot starts, this happens.

**Comment by Rocky-pup** [comment]
hmm, i haven't this problem, so i can't help

**Comment by Striker-Qc** [comment]
i have the same problem too

**Comment by JordanC28** [comment]
Do you use the version of the bot with local database?

**Comment by Rocky-pup** [comment]
As I can see 
.get(player.guld, "channel") 
Is enmap structure, so it's local, yes
