### ISSUE TITLE
Bug report start erela

### ISSUE THREAD

**Issue by Mioultigaming** [Tomato6966/Multipurpose-discord-bot#133]
## **What's your nodejs Version.**
> 16.14.0

## **What's the version you downloaded the bot?**
> From the releases e.g.: 11.0

## **Desktop (please complete the following information):**
> - OS: Windows
> - Version 10

## **Describe the bug**
> Bug is start bot

## **To Reproduce**
1. Execute the Command 'node index.js'
2. See error

## **Additional context, text and screenshots!**
```
/home/container/handlers/erela_events/events.js:97
          let channel = guild.channels.cache.get(client.musicsettings.get(player.guild, "channel"));
          ^^^

SyntaxError: Lexical declaration cannot appear in a single-statement context
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (/home/container/handlers/erela_events/creation.js:45:7)
    at module.exports (/home/container/handlers/erelahandler.js:5:39)
    at /home/container/index.js:123:43
    at Array.forEach (<anonymous>)
    at requirehandlers (/home/container/index.js:122:102)
    at Object.<anonymous> (/home/container/index.js:141:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
Provided token: OTU5MTkzODgyNDg5MzkzMjYy.YkYU6g.***************************
Preparing to connect to the gateway...
Hit a 429 while executing a request.
    Global  : false
    Method  : get
    Path    : /gateway/bot
    Route   : /gateway/bot
    Limit   : Infinity
    Timeout : 0ms
    Sublimit: 1145000ms





=== UNHANDLED REJECTION ===
Reason:  Error: Request failed with status code 400
    at createError (/home/container/node_modules/erela.js-spotify/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/container/node_modules/erela.js-spotify/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/container/node_modules/erela.js-spotify/node_modules/axios/lib/adapters/http.js:244:11)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
=== UNHANDLED REJECTION ===


```

**Comment by Tomato6966** [comment]
I cannot reproduce your error, as i am not hosting on a MACHINE which is BANNED FROM DISCORD PERMAMENTLY (global 429 error)

If you are on replit, this is common as OTHERS could get a BAN Which affects you too, as their IPS are shared.

try it on a LOCAL MACHINE and you'll see it works
