### ISSUE TITLE
ERROR WITH SHARDED VERSION

### ISSUE THREAD

**Issue by SHASHANK2341** [Tomato6966/Multipurpose-discord-bot#159]
C:\Users\n5463\OneDrive\Desktop\CODING\Multipurpose-discord-bot-sharded_with_mongo\node_modules\discord-hybrid-sharding\src\Core\ClusterManager.js:62
        if(options.keepAlive) throw new Error('keepAlive is not supported anymore on and above v1.6.0. Import it as plugin ("HeartBeatManager"), therefore check the libs readme');
                              ^

Error: keepAlive is not supported anymore on and above v1.6.0. Import it as plugin ("HeartBeatManager"), therefore check the libs readme
    at new ClusterManager (C:\Users\n5463\OneDrive\Desktop\CODING\Multipurpose-discord-bot-sharded_with_mongo\node_modules\discord-hybrid-sharding\src\Core\ClusterManager.js:62:37)
    at Object.<anonymous> (C:\Users\n5463\OneDrive\Desktop\CODING\Multipurpose-discord-bot-sharded_with_mongo\index.js:9:17)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by Tomato6966** [comment]
make sure to use the versions from the package.json and do not update the packages which have MAJOR BREAKING CHANGES!

npm i discord-hybrid-sharding@1.5
