### ISSUE TITLE
claim ticket

### ISSUE THREAD

**Issue by Alex441A** [Tomato6966/Multipurpose-discord-bot#173]
=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read property 'get' of undefined
    at Client.<anonymous> (/home/runner/Woop1/handlers/ticketevent.js:940:81)
    at Client.emit (node:events:406:35)
    at InteractionCreateAction.handle (/home/runner/Woop1/node_modules/discord.js/src/client/actions/InteractionCreate.js:74:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/runner/Woop1/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/runner/Woop1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/home/runner/Woop1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/Woop1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/Woop1/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/home/runner/Woop1/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/home/runner/Woop1/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/runner/Woop1/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/runner/Woop1/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/runner/Woop1/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.socketOnData (/home/runner/Woop1/node_modules/ws/lib/websocket.js:1192:35)
    at TLSSocket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
=== UNHANDLED REJECTION ===

**Comment by vuthanhtrung2010** [comment]
your databases?
