### ISSUE TITLE
Get General Help

### ISSUE THREAD

**Issue by Halvien** [Tomato6966/Multipurpose-discord-bot#174]
Im getting these error message: 

=== UNHANDLED REJECTION ===
Reason:  DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:279:15)
=== UNHANDLED REJECTION ===

{"timeout":250,"limit":1,"method":"put","path":"/channels/736917166145798214/messages/1015374535731720232/reactions/undefined:863876115584385074/@me","route":"/channels/736917166145798214/messages/:id/reactions","global":false}
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Y.json (/home/container/node_modules/petitio/dist/index.js:30:574)
    at ke.json (/home/container/node_modules/petitio/dist/index.js:30:2499)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Deadpool7518** [comment]
Join the Discord and you Can Ask Questions There! & Your bot is Missing permissions

**Comment by Halvien** [comment]
Discord link? THe links are invalid

**Comment by Halvien** [comment]
Pls help

**Comment by dev-jhon-ss** [comment]
> Im getting these error message:
> 
> === UNHANDLED REJECTION === Reason: DiscordAPIError: Missing Permissions at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:350:13) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:51:14) at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:279:15) === UNHANDLED REJECTION ===
> 
> {"timeout":250,"limit":1,"method":"put","path":"/channels/736917166145798214/messages/1015374535731720232/reactions/undefined:863876115584385074/@me","route":"/channels/736917166145798214/messages/:id/reactions","global":false} SyntaxError: Unexpected token in JSON at position 0 at JSON.parse () at Y.json (/home/container/node_modules/petitio/dist/index.js:30:574) at ke.json (/home/container/node_modules/petitio/dist/index.js:30:2499) at processTicksAndRejections (node:internal/process/task_queues:96:5)

@Halvien, you enabled intents for your bot in [Developer](https://discord.com/developers/applications) ?
