### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by ZappyGamingYTT** [Tomato6966/Multipurpose-discord-bot#185]
I get this error, because get and client.mutes is not defined, can any1 help?

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
    at CJ.<anonymous> (C:\Users\radem\OneDrive\Bureaublad\Multipurpose-discord-bot\handlers\mute.js:64:33)
    at CJ.fireOnTick (C:\Users\radem\OneDrive\Bureaublad\Multipurpose-discord-bot\node_modules\cron\lib\job.js:102:23)
    at Timeout.callbackWrapper [as _onTimeout] (C:\Users\radem\OneDrive\Bureaublad\Multipurpose-discord-bot\node_modules\cron\lib\job.js:174:10)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
    at CJ.<anonymous> (C:\Users\radem\OneDrive\Bureaublad\Multipurpose-discord-bot\handlers\mute.js:25:22)
    at CJ.fireOnTick (C:\Users\radem\OneDrive\Bureaublad\Multipurpose-discord-bot\node_modules\cron\lib\job.js:102:23)
    at Timeout.callbackWrapper [as _onTimeout] (C:\Users\radem\OneDrive\Bureaublad\Multipurpose-discord-bot\node_modules\cron\lib\job.js:174:10)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
=== UNHANDLED REJECTION ===

**Comment by YusiWar** [comment]
setup-ticket and setup-youtube its Not fixed

**Comment by vuthanhtrung2010** [comment]
database issue
