### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by PickstrYT** [Tomato6966/Multipurpose-discord-bot#20]
I am getting this error, how to fix it?

=== UNHANDLED REJECTION ===
Reason:  Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\Asus\Documents\Mini-Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250:15)        
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.login (C:\Users\Asus\Documents\Mini-Bot\node_modules\discord.js\src\client\Client.js:254:7)
=== UNHANDLED REJECTION ===

**Comment by shawn3308** [comment]
![image](https://user-images.githubusercontent.com/60691117/151197237-bf264b78-5b13-4417-b3d6-b4c93d635b18.png)
you need this on in the app

**Comment by PickstrYT** [comment]
oh ok
