### ISSUE TITLE
Cannot read properties of undefined (reading 'get') could anyone help me?

### ISSUE THREAD

**Issue by LeviAckerman1234** [Tomato6966/Multipurpose-discord-bot#47]
Cannot read properties of undefined (reading 'get') can anyone help me?

**Comment by jedd0888** [comment]
Can you please show the error in full

**Comment by LeviAckerman1234** [comment]
=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
    at CronJob.<anonymous> (/Users/gurveerbal/Multipurpose-discord-bot/handlers/mute.js:64:33)
    at CronJob.fireOnTick (/Users/gurveerbal/Multipurpose-discord-bot/node_modules/cron/lib/cron.js:600:23)
    at Timeout.callbackWrapper [as _onTimeout] (/Users/gurveerbal/Multipurpose-discord-bot/node_modules/cron/lib/cron.js:667:10)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
=== UNHANDLED REJECTION ===





TypeError: Cannot read properties of undefined (reading 'get')
    at check_voice_channels (/Users/gurveerbal/Multipurpose-discord-bot/handlers/functions.js:2106:50)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
TypeError: Cannot read properties of undefined (reading 'get')
    at check_voice_channels (/Users/gurveerbal/Multipurpose-discord-bot/handlers/functions.js:2106:50)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
TypeError: Cannot read properties of undefined (reading 'get')
    at check_voice_channels (/Users/gurveerbal/Multipurpose-discord-bot/handlers/functions.js:2106:50)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
TypeError: Cannot read properties of undefined (reading 'get')
    at check_voice_channels (/Users/gurveerbal/Multipurpose-discord-bot/handlers/functions.js:2106:50)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
=== UNCAUGHT EXCEPTION MONITOR ===






=== UNCAUGHT EXCEPTION ===
Exception:  TypeError: Cannot read properties of undefined (reading 'filter')
    at CronJob.<anonymous> (/Users/gurveerbal/Multipurpose-discord-bot/handlers/autonsfw.js:13:38)
    at CronJob.fireOnTick (/Users/gurveerbal/Multipurpose-discord-bot/node_modules/cron/lib/cron.js:600:23)
    at Timeout.callbackWrapper [as _onTimeout] (/Users/gurveerbal/Multipurpose-discord-bot/node_modules/cron/lib/cron.js:667:10)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
=== UNCAUGHT EXCEPTION ===










=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
    at CronJob.<anonymous> (/Users/gurveerbal/Multipurpose-discord-bot/handlers/mute.js:25:22)
    at CronJob.fireOnTick (/Users/gurveerbal/Multipurpose-discord-bot/node_modules/cron/lib/cron.js:600:23)
    at Timeout.callbackWrapper [as _onTimeout] (/Users/gurveerbal/Multipurpose-discord-bot/node_modules/cron/lib/cron.js:667:10)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
=== UNHANDLED REJECTION ===










=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
    at CronJob.<anonymous> (/Users/gurveerbal/Multipurpose-discord-bot/handlers/mute.js:64:33)
    at CronJob.fireOnTick (/Users/gurveerbal/Multipurpose-discord-bot/node_modules/cron/lib/cron.js:600:23)
    at Timeout.callbackWrapper [as _onTimeout] (/Users/gurveerbal/Multipurpose-discord-bot/node_modules/cron/lib/cron.js:667:10)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
=== UNHANDLED REJECTION ===

> Can you please show the error in full

**Comment by LeviAckerman1234** [comment]
any fix on this?

**Comment by philipp435** [comment]
hello any1 here?

**Comment by LeviAckerman1234** [comment]
hello?

**Comment by LeviAckerman1234** [comment]
its breaking the entire code

**Comment by LeviAckerman1234** [comment]
anyone there?

**Comment by Tomato6966** [comment]
while u are starting the BOT, it could not load the DATABASES

make sure to do npm install and have nodejs as well as python installed
make sure the installation process works without having errors

if u are planning on reinstalling it, make sure to delete node_modules

**Comment by LeviAckerman1234** [comment]
ah u think python would be the problem? i forgot to download it lol

**Comment by LeviAckerman1234** [comment]
i downloaded python but the same error keeps coming up

**Comment by LeviAckerman1234** [comment]
plz help me bro

**Comment by LeviAckerman1234** [comment]
hello?

**Comment by Tomato6966** [comment]
I can just repeat

or check the  https://github.com/Tomato6966/Multipurpose-discord-bot/wiki
MAybe enmap installation guide helps?
https://enmap.evie.dev/install/

while u are starting the BOT, it could not load the DATABASES

make sure to do npm install and have nodejs as well as python installed
make sure the installation process works without having errors

if u are planning on reinstalling it, make sure to delete node_modules
