### ISSUE TITLE
There Is Some Error When I Run The Bot On Replit! Please Help!

### ISSUE THREAD

**Issue by dragN-TheGodLike** [Tomato6966/Multipurpose-discord-bot#49]
[MP Bot Issue On REPLIT.zip](https://github.com/Tomato6966/Multipurpose-discord-bot/files/8007679/MP.Bot.Issue.On.REPLIT.zip)

This Is The Issue!

**Comment by dragN-TheGodLike** [comment]
`PS C:\Users\INTERSTELLER DRAGN\Multipurpose-discord-bot> java -jar Lavalink.jar
2022-02-05 16:46:33.722  INFO 19576 --- [           main] lavalink.server.Launcher                 : 

       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

        Version:        3.4
        Build:          1257
        Build time:     26.10.2021 14:18:37 UTC
        Branch          master
        Commit:         a364833
        Commit time:    26.10.2021 14:15:20 UTC
        JVM:            11.0.11
        Lavaplayer      1.3.96-original

2022-02-05 16:46:33.843  INFO 19576 --- [           main] lavalink.server.Launcher                 : Starting Launcher on THIS-PC-IS-OP with PID 19576 (C:\Users\INTERSTELLER DRAGN\Multipurpose-discord-bot\Lavalink.jar started by INTERSTELLER DRAGN in C:\Users\INTERSTELLER DRAGN\Multipurpose-discord-bot)
2022-02-05 16:46:33.844  INFO 19576 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2022-02-05 16:46:33.986  WARN 19576 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2022-02-05 16:46:35.170  WARN 19576 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-05 16:46:35.208  INFO 19576 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2022-02-05 16:46:35.208  INFO 19576 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1309 ms
2022-02-05 16:46:35.520  WARN 19576 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2022-02-05 16:46:35.777  INFO 19576 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2022-02-05 16:46:36.996  INFO 19576 --- [           main] lavalink.server.config.KoeConfiguration  : OS: Windows 10, Arch: amd64
2022-02-05 16:46:36.996  WARN 19576 --- [           main] lavalink.server.config.KoeConfiguration  : This system and architecture appears to not support native audio sending! GC pauses may cause your bot to stutter during playback.
2022-02-05 16:46:37.224  INFO 19576 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2022-02-05 16:46:37.523  INFO 19576 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2022-02-05 16:46:37.534  INFO 19576 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2022-02-05 16:46:37.599  INFO 19576 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-02-05 16:46:37.603 ERROR 19576 --- [           main] lavalink.server.Launcher                 : Application failed

org.springframework.boot.web.server.PortInUseException: Port 8080 is already in use
        at org.springframework.boot.web.embedded.undertow.UndertowServletWebServer.start(UndertowServletWebServer.java:154) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:297) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at lavalink.server.Launcher.main(Launcher.kt:127) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[Lavalink.jar:na]

2022-02-05 16:46:37.610 ERROR 19576 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 8080 was already in use.

Action:

Identify and stop the process that's listening on port 8080 or configure this application to listen on another port.

2022-02-05 16:46:37.616  INFO 19576 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'     
2022-02-05 16:46:37.618  INFO 19576 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring disabled.
`


i also get this when using lavalink

**Comment by jedd0888** [comment]
Web server failed to start. Port 8080 was already in use.

**Comment by dragN-TheGodLike** [comment]
> Web server failed to start. Port 8080 was already in use. Make sure this port is free for the webserver/change the port

how to change it? @jedd0888

**Comment by Tomato6966** [comment]
U are trying to selfhost lavalink

if u put the `Lavalink.jar` file and the `application.yml` file not in the same folder, lavalink uses the default port `8080`

but u prob. don't want to use this port

so put both files in the same folder and adjust the port in application.yml to something like: `2333` (it must match with config.json
