### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ItsMeRioooo** [Tomato6966/Multipurpose-discord-bot#54]
=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'wrongcolor')
    at Object.run (/home/container/commands/👑 Owner/reloadallcmds.js:25:22)
    at module.exports (/home/container/events/guild/messageCreate.js:295:17)
    at Client.emit (node:events:532:35)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:520:28)
    at Receiver.receiverOnMessage (/home/container/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (node:events:520:28)
    at Receiver.dataMessage (/home/container/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/container/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/container/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/container/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:390:12)
    at _write (node:internal/streams/writable:331:10)
    at Receiver.Writable.write (node:internal/streams/writable:335:10)
    at TLSSocket.socketOnData (/home/container/node_modules/ws/lib/websocket.js:1192:35)
    at TLSSocket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:324:12)
=== UNHANDLED REJECTION ===

when typing .reloadallcmds i got this error

**Comment by jedd0888** [comment]
I found the bug, i will make a fix in a sec for it

**Comment by jedd0888** [comment]
I checked the error again
It seems like its a DB error from your side, make sure that the wrongcolor value exists under the embed object, in your guild id key

**Comment by ItsMeRioooo** [comment]
wait lemme check

**Comment by jedddg** [comment]
> 

resolved?
