### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ItsMeRioooo** [Tomato6966/Multipurpose-discord-bot#55]
=== UNHANDLED REJECTION ===
Reason:  TypeError: this.options.embeds?.map is not a function
    at MessagePayload.resolveData (/home/container/node_modules/discord.js/src/structures/MessagePayload.js:195:36)
    at MessageManager.edit (/home/container/node_modules/discord.js/src/managers/MessageManager.js:130:8)
    at Message.edit (/home/container/node_modules/discord.js/src/structures/Message.js:702:34)
    at InteractionCollector.<anonymous> (/home/container/commands/🚫 Administration/sync-invites.js:121:22)
    at InteractionCollector.emit (node:events:532:35)
    at InteractionCollector.stop (/home/container/node_modules/discord.js/src/structures/interfaces/Collector.js:198:10)
    at Timeout.<anonymous> (/home/container/node_modules/discord.js/src/structures/interfaces/Collector.js:88:61)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
=== UNHANDLED REJECTION ===

when using sync-invites

**Comment by jedd0888** [comment]
can you explain how you can reproduce this error? solely for testing reasons

**Comment by SukiPlayz** [comment]
> can you explain how you can reproduce this error? solely for testing reasons

Just run the sync-invites command. It gives the error there. Same happened to me.

**Comment by jedd0888** [comment]
ill try it later

**Comment by malbouy** [comment]
Okay I'll try fixing this

**Comment by malbouy** [comment]
Done I got a solution, will deploy an update after reviewing other bugs as well :)
