### ISSUE TITLE
cannot read properties of undefined (reading 'get)

### ISSUE THREAD

**Issue by TheGamer3514** [Tomato6966/Multipurpose-discord-bot#68]
## **What's your nodejs Version.**
Show the output of: `node -v`
16.14.0
![image](https://user-images.githubusercontent.com/79448904/153847668-f8a1fef5-7674-460f-bd4d-77746a071f9e.png)
this error occurs every time i attempt to run a command

**Comment by TheGamer3514** [comment]
there are no errors when i do npm install, how do i check the databases

**Comment by TheGamer3514** [comment]
i think the database is fine, the error in console:
    at Client.<anonymous> (/home/container/handlers/erela_events/musicsystem.js:316:47)
    at Client.emit (node:events:532:35)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:520:28)
    at Receiver.receiverOnMessage (/home/container/node_modules/ws/lib/websocket.js:1137:20)
    at Receiver.emit (node:events:520:28)
    at Receiver.dataMessage (/home/container/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/container/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/container/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/container/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.socketOnData (/home/container/node_modules/ws/lib/websocket.js:1231:35)
    at TLSSocket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)

**Comment by malbouy** [comment]
> i think the database is fine, the error in console: at Client. (/home/container/handlers/erela_events/musicsystem.js:316:47) at Client.emit (node:events:532:35) at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14) at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32) at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31) at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22) at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10) at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:199:18) at WebSocket.emit (node:events:520:28) at Receiver.receiverOnMessage (/home/container/node_modules/ws/lib/websocket.js:1137:20) at Receiver.emit (node:events:520:28) at Receiver.dataMessage (/home/container/node_modules/ws/lib/receiver.js:528:14) at Receiver.getData (/home/container/node_modules/ws/lib/receiver.js:446:17) at Receiver.startLoop (/home/container/node_modules/ws/lib/receiver.js:148:22) at Receiver._write (/home/container/node_modules/ws/lib/receiver.js:83:10) at writeOrBuffer (node:internal/streams/writable:389:12) at _write (node:internal/streams/writable:330:10) at Receiver.Writable.write (node:internal/streams/writable:334:10) at TLSSocket.socketOnData (/home/container/node_modules/ws/lib/websocket.js:1231:35) at TLSSocket.emit (node:events:520:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9)

Can u send the actual error logs rather than sending the almost useless bit of information there? Actual logs are above what you sent.
