### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by MondoPIX** [Tomato6966/Multipurpose-discord-bot#70]
## **What's your nodejs Version.**
> Show the output of: `node -v`
v17.2.0

## **What's the version you downloaded the bot?**
> From the releases e.g.: 10.2.0
10.3.0

## **Desktop (please complete the following information):**
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"

## **Describe the bug**
> A clear and concise description of what the bug is.

```
~/Multipurpose-discord-bot$ npm start

> clan_bot@11.0.0 start
> node index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- /home/botdiscord/Multipurpose-discord-bot/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/index.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/botdiscord/Multipurpose-discord-bot/index.js' ]
}

Node.js v17.2.0
```

**Comment by MondoPIX** [comment]
i ran the command to install it `npm i dotenv`

this is what it gave me after the `npm start` run


```
~/Multipurpose-discord-bot$ npm i dotenv

added 1 package, and audited 522 packages in 6s

55 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (7 moderate, 2 high)

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
~/Multipurpose-discord-bot$ npm audit
# npm audit report

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
No fix available
node_modules/tiktok-scraper/node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/tiktok-scraper/node_modules/strip-ansi
    cliui  4.0.0 - 5.0.0
    Depends on vulnerable versions of strip-ansi
    Depends on vulnerable versions of wrap-ansi
    node_modules/tiktok-scraper/node_modules/cliui
      yargs  10.1.0 - 15.0.0
      Depends on vulnerable versions of cliui
      Depends on vulnerable versions of string-width
      node_modules/tiktok-scraper/node_modules/yargs
        tiktok-scraper  *
        Depends on vulnerable versions of yargs
        node_modules/tiktok-scraper
    string-width  2.1.0 - 4.1.0
    Depends on vulnerable versions of strip-ansi
    node_modules/tiktok-scraper/node_modules/string-width
      wrap-ansi  3.0.0 - 6.1.0
      Depends on vulnerable versions of string-width
      Depends on vulnerable versions of strip-ansi
      node_modules/tiktok-scraper/node_modules/wrap-ansi

axios  <=0.21.1
Severity: high
Incorrect Comparison in axios - https://github.com/advisories/GHSA-cph5-m8f7-6c5x
Server-Side Request Forgery in Axios - https://github.com/advisories/GHSA-4w2v-q235-vp99
No fix available
node_modules/erela.js-spotify/node_modules/axios
  erela.js-spotify  *
  Depends on vulnerable versions of axios
  node_modules/erela.js-spotify

9 vulnerabilities (7 moderate, 2 high)

Some issues need review, and may require choosing
a different dependency.
botdiscord@pix-server2:~/Multipurpose-discord-bot$ npm start

> clan_bot@11.0.0 start
> node index.js

Welcome to SERVICE HANDLER /--/ By https://milrato.eu /--/ Discord: Tomato#6966
[x] :: Now loading the Commands ...
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord-buttons/src/v12/Classes/clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
[x] :: LOADED THE 618 COMMANDS after: 13890ms
[x] :: Now loading the Database...
[x] :: LOADED THE DATABASES after: 4547ms
[x] :: Now loading the Events ...
[x] :: LOADED THE 15 EVENTS after: 21ms


     ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
     ┃                                                                  ┃
     ┃ Logging into the BOT...                                          ┃
     ┃                                                                  ┃
     ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
/home/botdiscord/Multipurpose-discord-bot/handlers/erela_events/events.js:97
          let channel = guild.channels.cache.get(client.musicsettings.get(player.guild, "channel"));
          ^^^

SyntaxError: Lexical declaration cannot appear in a single-statement context
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1026:15)
    at Module._compile (node:internal/modules/cjs/loader:1061:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (/home/botdiscord/Multipurpose-discord-bot/handlers/erela_events/creation.js:45:7)
    at module.exports (/home/botdiscord/Multipurpose-discord-bot/handlers/erelahandler.js:5:39)
    at /home/botdiscord/Multipurpose-discord-bot/index.js:123:43
    at Array.forEach (<anonymous>)
    at requirehandlers (/home/botdiscord/Multipurpose-discord-bot/index.js:122:102)
    at Object.<anonymous> (/home/botdiscord/Multipurpose-discord-bot/index.js:141:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
Provided token: Mzg3MjI1MzgxNTc0NTQxMzEz.WiVFvQ.***************************
Preparing to connect to the gateway...
[WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 990
[WS => Manager] Using the recommended shard count provided by Discord: 1
[WS => Manager] Spawning shards: 0
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 9
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
[WS => Shard 0] [CONNECTED] Took 279ms
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] Setting a heartbeat interval for 41250ms.
[WS => Shard 0] [IDENTIFY] Shard 0/1 with intents: 14335
[WS => Shard 0] [CLOSE]
    Event Code: 4014
    Clean     : true
    Reason    : Disallowed intent(s).
[WS => Shard 0] Clearing the heartbeat interval.
 || <==> || [Tue Feb 15 2022 14:55:01] || <==> || Shard #0 Disconnected || <==> ||
[WS => Shard 0] DISALLOWED_INTENTS
[WS => Manager] Manager was destroyed. Called by:
Error [MANAGER_DESTROYED]: Manager was destroyed.
    at WebSocketManager.destroy (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:322:54)
    at Client.destroy (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord.js/src/client/Client.js:284:13)
    at Client.login (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord.js/src/client/Client.js:257:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[WS => Shard 0] WS State: CLOSED





=== UNHANDLED REJECTION ===
Reason:  Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.login (/home/botdiscord/Multipurpose-discord-bot/node_modules/discord.js/src/client/Client.js:254:7)
=== UNHANDLED REJECTION ===





[TWITCH] | Tue 15-02-2022 14:57:00.0160 ::  Checking Accounts - Tuesday, February 15, 2022 2:57 PM
 [TWITER] :: Checking Accounts
 [TWITER] :: NO USERIDS:

```

**Comment by demauye** [comment]
same. me too
