### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by WilardzySenpai** [Tomato6966/Multipurpose-discord-bot#86]
```
=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read property 'get' of undefined
    at change_status (/home/runner/Proteksiyon-Release/events/client/ready.js:47:34)
    at module.exports (/home/runner/Proteksiyon-Release/events/client/ready.js:35:5)
    at Client.emit (node:events:406:35)
    at WebSocketManager.triggerClientReady (/home/runner/Proteksiyon-Release/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:17)
    at WebSocketManager.checkShardsReady (/home/runner/Proteksiyon-Release/node_modules/discord.js/src/client/websocket/WebSocketManager.js:367:10)
    at WebSocketShard.<anonymous> (/home/runner/Proteksiyon-Release/node_modules/discord.js/src/client/websocket/WebSocketManager.js:189:14)
    at WebSocketShard.emit (node:events:394:28)
    at WebSocketShard.checkReady (/home/runner/Proteksiyon-Release/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (/home/runner/Proteksiyon-Release/node_modules/discord.js/src/client/websocket/WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (/home/runner/Proteksiyon-Release/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/Proteksiyon-Release/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/home/runner/Proteksiyon-Release/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/home/runner/Proteksiyon-Release/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/runner/Proteksiyon-Release/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/runner/Proteksiyon-Release/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/runner/Proteksiyon-Release/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.socketOnData (/home/runner/Proteksiyon-Release/node_modules/ws/lib/websocket.js:1192:35)
=== UNHANDLED REJECTION ===
```

**Comment by jedddg** [comment]
can you provide the code too?
