### ISSUE TITLE
Bug report / Menu Ticket no ticket claimed message

### ISSUE THREAD

**Issue by protyodev** [Tomato6966/Multipurpose-discord-bot#90]
When trying to claim a ticket

14|SYSTEM_BOTS_Script  | === UNHANDLED REJECTION ===
14|SYSTEM_BOTS_Script  | Reason:  TypeError: Cannot read properties of undefined (reading 'get')
14|SYSTEM_BOTS_Script  |     at Client.<anonymous> (/home/servicebots/SYSTEMBOTS/Script/handlers/ticketevent.js:940:81)
14|SYSTEM_BOTS_Script  |     at Client.emit (node:events:402:35)
14|SYSTEM_BOTS_Script  |     at InteractionCreateAction.handle (/home/servicebots/SYSTEMBOTS/Script/node_modules/discord.js/src/client/actions/InteractionCreate.js:74:12)
14|SYSTEM_BOTS_Script  |     at Object.module.exports [as INTERACTION_CREATE] (/home/servicebots/SYSTEMBOTS/Script/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
14|SYSTEM_BOTS_Script  |     at WebSocketManager.handlePacket (/home/servicebots/SYSTEMBOTS/Script/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
14|SYSTEM_BOTS_Script  |     at WebSocketShard.onPacket (/home/servicebots/SYSTEMBOTS/Script/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
14|SYSTEM_BOTS_Script  |     at WebSocketShard.onMessage (/home/servicebots/SYSTEMBOTS/Script/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
14|SYSTEM_BOTS_Script  |     at WebSocket.onMessage (/home/servicebots/SYSTEMBOTS/Script/node_modules/ws/lib/event-target.js:199:18)
14|SYSTEM_BOTS_Script  |     at WebSocket.emit (node:events:390:28)
14|SYSTEM_BOTS_Script  |     at Receiver.receiverOnMessage (/home/servicebots/SYSTEMBOTS/Script/node_modules/ws/lib/websocket.js:1137:20)
14|SYSTEM_BOTS_Script  |     at Receiver.emit (node:events:390:28)
14|SYSTEM_BOTS_Script  |     at Receiver.dataMessage (/home/servicebots/SYSTEMBOTS/Script/node_modules/ws/lib/receiver.js:528:14)
14|SYSTEM_BOTS_Script  |     at Receiver.getData (/home/servicebots/SYSTEMBOTS/Script/node_modules/ws/lib/receiver.js:446:17)
14|SYSTEM_BOTS_Script  |     at Receiver.startLoop (/home/servicebots/SYSTEMBOTS/Script/node_modules/ws/lib/receiver.js:148:22)
14|SYSTEM_BOTS_Script  |     at Receiver._write (/home/servicebots/SYSTEMBOTS/Script/node_modules/ws/lib/receiver.js:83:10)
14|SYSTEM_BOTS_Script  |     at writeOrBuffer (node:internal/streams/writable:389:12)
14|SYSTEM_BOTS_Script  |     at _write (node:internal/streams/writable:330:10)
14|SYSTEM_BOTS_Script  |     at Receiver.Writable.write (node:internal/streams/writable:334:10)
14|SYSTEM_BOTS_Script  |     at TLSSocket.socketOnData (/home/servicebots/SYSTEMBOTS/Script/node_modules/ws/lib/websocket.js:1231:35)
14|SYSTEM_BOTS_Script  |     at TLSSocket.emit (node:events:390:28)
14|SYSTEM_BOTS_Script  |     at addChunk (node:internal/streams/readable:315:12)
14|SYSTEM_BOTS_Script  |     at readableAddChunk (node:internal/streams/readable:289:9)

**Comment by Tomato6966** [comment]
make sure the databases get created correctly.

**Comment by protyodev** [comment]
How do I check if its correct or not?

**Comment by vuthanhtrung2010** [comment]
> How do I check if its correct or not?

try to delete database then put database again in menuticket folder!
