### ISSUE TITLE
Bug report /info avatar

### ISSUE THREAD

**Issue by JordanC28** [Tomato6966/Multipurpose-discord-bot#94]
## **What's your nodejs Version.**
> Show the output of: `v16.14.0`

## **What's the version you downloaded the bot?**
> From the releases e.g.: 10.3.0

## **Desktop (please complete the following information):**
> - OS: Windows
> - Version 11

## **Describe the bug**
> When using the slashcommand info-avatar it shows an error in console and there is no response from the application..

## **To Reproduce**
> Steps to reproduce the behavior e.g:
1. Execute the Command /info avatar '
2. TypeError: message.reply is not a function
    at Object.run (/home/container/slashCommands/Info/avatar.js:61:15)
    at module.exports (/home/container/events/guild/interactionCreate.js:228:11)
    at Client.emit (node:events:532:35)
    at InteractionCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:74:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:520:28)
    at Receiver.receiverOnMessage (/home/container/node_modules/ws/lib/websocket.js:1137:20)
    at Receiver.emit (node:events:520:28)
    at Receiver.dataMessage (/home/container/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/container/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/container/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/container/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.socketOnData (/home/container/node_modules/ws/lib/websocket.js:1231:35)
    at TLSSocket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)

## **Expected behavior**
> Must display a user's avatar.

## **Additional context, text and screenshots!**
![image](https://user-images.githubusercontent.com/66105915/158646944-d935cfeb-b805-47ed-9f91-9df39cb12f3e.png)
![Captura de pantalla (268)](https://user-images.githubusercontent.com/66105915/158647167-1d8e1654-f80d-4e0a-87bb-e024f888855e.png)

**Comment by JordanC28** [comment]
**Fix**
Add **//** in line 61

![image](https://user-images.githubusercontent.com/66105915/158690097-5d51e416-45f8-44cb-a5a6-485d888c5177.png)
